2022-02-24 09:53:13.620 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No existe el archivo 
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes2.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_281]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_281]
	at java.io.FileReader.<init>(FileReader.java:72) ~[?:1.8.0_281]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:33) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2022-02-24 10:04:51.270 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - error al armar cliente en la linea:0912313123,Beatriz Rosales
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:24) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:44) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2022-02-24 10:05:54.925 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - error al armar cliente en la linea:0912313123,Beatriz Rosales
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:23) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:40) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2022-02-24 10:06:56.883 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No existe el archivo 
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes2.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_281]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_281]
	at java.io.FileReader.<init>(FileReader.java:72) ~[?:1.8.0_281]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:37) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2022-02-24 10:08:42.560 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No existe el archivo 
java.io.FileNotFoundException: C:\Users\jasmi\OneDrive\Documents\archivo\Clientes2.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_281]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_281]
	at java.io.FileReader.<init>(FileReader.java:72) ~[?:1.8.0_281]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:37) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2022-02-24 10:31:27.708 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - error al armar cliente en la linea:0912313123,Beatriz Rosales
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:23) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:40) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
